# Generated by Django 3.1.3 on 2020-11-13 04:34

import disaster_broadcaster.filepaths.FilePath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', upload_to=disaster_broadcaster.filepaths.FilePath.FilePath.avatar),
        ),
    ]
