# Generated by Django 3.1.3 on 2020-11-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='date_updated',
        ),
    ]
