# Generated by Django 3.1.3 on 2020-11-14 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0007_auto_20201114_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{1,15}$')]),
        ),
    ]
