# Generated by Django 3.1.3 on 2020-11-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0008_auto_20201114_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('guide_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CharityOrganization',
            new_name='Organization',
        ),
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.CharField(default='singer', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disaster_broadcaster.country'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disaster_broadcaster.category'),
        ),
        migrations.DeleteModel(
            name='DisasterCategory',
        ),
    ]
