# Generated by Django 3.1.3 on 2020-11-27 03:09

import disaster_broadcaster.filepaths.FilePath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0009_auto_20201121_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_page',
            field=models.URLField(default='https://donate.tpfund.org/campaign/izmir-turkey-earthquake-relief-fund/c309729'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(null=True, upload_to=disaster_broadcaster.filepaths.FilePath.FilePath.post_upload),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=1024),
        ),
    ]
