# Generated by Django 3.1.3 on 2020-11-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0010_auto_20201127_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
