# Generated by Django 3.1.3 on 2020-11-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0011_news_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='media',
        ),
    ]
