# Generated by Django 3.1.3 on 2020-11-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0014_auto_20201130_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('1', 'Like'), ('2', 'Sad'), ('3', 'Love')], default='3', max_length=3),
        ),
    ]
