# Generated by Django 3.1.3 on 2020-11-30 19:57

import disaster_broadcaster.filepaths.FilePath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0015_auto_20201130_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to=disaster_broadcaster.filepaths.FilePath.FilePath.avatar),
        ),
    ]
