# Generated by Django 3.1.3 on 2020-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0016_auto_20201130_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='emergency_url',
        ),
    ]
