# Generated by Django 3.1.3 on 2020-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0017_remove_country_emergency_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.URLField(default='https://increasify.com.au/wp-content/uploads/2016/08/default-image.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://www.flaticon.com/svg/static/icons/svg/3815/3815448.svg'),
        ),
    ]
