# Generated by Django 3.1.3 on 2020-12-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0018_auto_20201205_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.URLField(default='https://increasify.com.au/wp-content/uploads/2016/08/default-image.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://www.flaticon.com/svg/static/icons/svg/3815/3815448.svg', max_length=1000),
        ),
    ]
