# Generated by Django 3.1.3 on 2020-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_broadcaster', '0019_auto_20201205_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://www.flaticon.com/svg/static/icons/svg/3815/3815323.svg', max_length=1000),
        ),
    ]
